### PR TITLE
TST: test models with inherited unit tests from pysat

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

Addresses #6 (partial)

- Tests the ucar_tiegcm object with the instrument test routines from pysat.  
- Updates properties of ucar_tiegcm to be consistent with pysat 3.0.0 changes

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality
      to not work as expected)
- This change requires a documentation update

# How Has This Been Tested?

pytest -vs

**Test Configuration**:
* Mac OS X 10.15.6
* python 3.7.3

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] Add a note to ``CHANGELOG.md``, summarizing the changes

# Notes

- Tied to pysat/pysat#391 for now.  Will update to develop-3 once that is merged.
- In a general case, needs modifications for downloaded instruments.  Current code will clear `first` and `second` flags.  No downloaded models currently here.

### CODE REVIEW

**Comment by jklenzing** [comment]
Path forward: Update pysat/pysat#391 to not initialize any instruments so `clear` is not needed here.

**Comment by jklenzing** [comment]
Fixed the travis branch now that pysat/pysat#391 is merged.  Ready for review.

**Comment by aburrell** [comment]
It looks like GitHub hasn't updated develop yet.  Recommend waiting and rerunning the CI tests.

**Comment by jklenzing** [comment]
I forgot to update the last minute class rename here.  Trying again, though may just wait for github to stop having server issues.

**Comment by aburrell** [comment]
Yeah, I tried to get it to restart on travis, and github needs to catch up :(

**Pull request merged**
