### PR TITLE
ENH: Load multiple days

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses #(issue)

Adds support for loading multiple filenames within `.load` methods for SAMI and TIEGCM.

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details for
your test configuration

- Tested locally by registering pysatModels.models and loading a UCAR-TIEGCM file.

**Test Configuration**:
* macOS Catalina 
* 10.15.4

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
I believe this is ready for review @aburrell . There are no tests. I could very well be wrong but I don't think tests are up and running here yet.

**Comment by aburrell** [comment]
Tests were up and running here, efforts were concentrated on improving coverage.  It looks like the recent breaking changes weren't fully propagated to this module.

**Review by aburrell — COMMENTED** [review]
Theoretically the code looks good.  Have you tested it locally on your TIEGCM data?

**Comment by rstoneback** [comment]
> Theoretically the code looks good. Have you tested it locally on your TIEGCM data?

Example below.
```
In [1]: import pysat                                                                                                                                                                                                        

In [2]: import pysatModels                                                                                                                                                                                                  

In [3]: pysat.utils.registry.register_by_module(pysatModels.models)                                                                                                                                                         
pysat WARNING: Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).
pysat WARNING: Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).

In [4]: ucar = pysat.Instrument('ucar', 'tiegcm')                                                                                                                                                                           

In [5]: ucar.files.files                                                                                                                                                                                                    
Out[5]: 
0
2018-05-29    tiegcm_icon_merg2.0_totTgcm.s_149_2018.nc
Name: 1, dtype: object

In [6]: ucar.load(2018, 149)                                                                                                                                                                                                
/Users/russellstoneback/Code/pysat/pysat/_meta.py:617: UserWarning: Array elements are not allowed in meta. Dropping input : initial_mtime
  warnings.warn(' '.join(('Array elements are',

In [7]: ucar.data                                                                                                                                                                                                           
Out[7]: 
<xarray.Dataset>
Dimensions:             (dtidedim: 2, ilev: 57, imlev: 63, lat: 72, lev: 57, lon: 144, mlat: 97, mlev: 63, mlon: 81, mtimedim: 3, sdtidedim: 10, time: 24)
Coordinates:
  * time                (time) datetime64[ns] 2009-05-29T01:00:00 ... 2009-05-30
  * lon                 (lon) float64 -180.0 -177.5 -175.0 ... 172.5 175.0 177.5
  * lat                 (lat) float64 -88.75 -86.25 -83.75 ... 83.75 86.25 88.75
  * lev                 (lev) float64 -6.875 -6.625 -6.375 ... 6.625 6.875 7.125
  * ilev                (ilev) float64 -7.0 -6.75 -6.5 -6.25 ... 6.5 6.75 7.0
  * mlon                (mlon) float64 -180.0 -175.5 -171.0 ... 175.5 180.0
  * mlat                (mlat) float64 -90.0 -88.12 -86.24 ... 86.24 88.12 90.0
  * mlev                (mlev) float64 -8.25 -8.0 -7.75 -7.5 ... 6.75 7.0 7.25
  * imlev               (imlev) float64 -8.5 -8.25 -8.0 -7.75 ... 6.5 6.75 7.0
    LBC                 float64 ...
Dimensions without coordinates: dtidedim, mtimedim, sdtidedim
Data variables:
    mtime               (time, mtimedim) int32 ...
    year                (time) int32 ...
....
```

**Comment by aburrell** [comment]
Thanks for making the fixes @rstoneback!  Can it now load more than one day as well?

**Comment by rstoneback** [comment]
> Theoretically the code looks good. Have you tested it locally on your TIEGCM data?

Yes! I did find some things to change to go with the latest develop-3.

```
In [1]: import pysat                                                                                                                                                                                                        

In [2]: import pysatModels                                                                                                                                                                                                  

In [3]: pysat.utils.registry.register_by_module(pysatModels.models)                                                                                                                                                         
pysat WARNING: Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).
pysat WARNING: Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).

In [4]: ucar = pysat.Instrument('ucar', 'tiegcm')                                                                                                                                                                           

In [5]: ucar.files.files                                                                                                                                                                                                    
Out[5]: 
0
2018-05-29    tiegcm_icon_merg2.0_totTgcm.s_149_2018.nc
Name: 1, dtype: object

In [6]: ucar.load(2018, 149)                                                                                                                                                                                                
/Users/russellstoneback/Code/pysat/pysat/_meta.py:617: UserWarning: Array elements are not allowed in meta. Dropping input : initial_mtime
  warnings.warn(' '.join(('Array elements are',

In [7]: ucar.data                                                                                                                                                                                                           
Out[7]: 
<xarray.Dataset>
Dimensions:             (dtidedim: 2, ilev: 57, imlev: 63, lat: 72, lev: 57, lon: 144, mlat: 97, mlev: 63, mlon: 81, mtimedim: 3, sdtidedim: 10, time: 24)
Coordinates:
  * time                (time) datetime64[ns] 2009-05-29T01:00:00 ... 2009-05-30
  * lon                 (lon) float64 -180.0 -177.5 -175.0 ... 172.5 175.0 177.5
  * lat                 (lat) float64 -88.75 -86.25 -83.75 ... 83.75 86.25 88.75
  * lev                 (lev) float64 -6.875 -6.625 -6.375 ... 6.625 6.875 7.125
  * ilev                (ilev) float64 -7.0 -6.75 -6.5 -6.25 ... 6.5 6.75 7.0
  * mlon                (mlon) float64 -180.0 -175.5 -171.0 ... 175.5 180.0
  * mlat                (mlat) float64 -90.0 -88.12 -86.24 ... 86.24 88.12 90.0
  * mlev                (mlev) float64 -8.25 -8.0 -7.75 -7.5 ... 6.75 7.0 7.25
  * imlev               (imlev) float64 -8.5 -8.25 -8.0 -7.75 ... 6.5 6.75 7.0
    LBC                 float64 ...
Dimensions without coordinates: dtidedim, mtimedim, sdtidedim
Data variables:
    mtime               (time, mtimedim) int32 ...
    year                (time) int32 ...
......
```

> Thanks for making the fixes @rstoneback! 

You are welcome.

>Can it now load more than one day as well?

I don't have more than one day of TIEGCM data locally to demonstrate that directly. But yes, the pysat load_netcdf4 does work with multiple files and xarray (and pandas!). It is part of the unit testing over in the pysat load_data_range branch.

**Comment by aburrell** [comment]
> I don't have more than one day of TIEGCM data locally to demonstrate that directly. 

That's a shame.  I suppose it reveals the distrust I have for our unit tests :-P  I'm waiting on the unit tests to complete before approving this.

**Comment by rstoneback** [comment]
> > I don't have more than one day of TIEGCM data locally to demonstrate that directly.
> 
> That's a shame. 

Yeah. I do have some SAMI data though. Copying things over. I'll update.

> I suppose it reveals the distrust I have for our unit tests :-P I'm waiting on the unit tests to complete before approving this.

No worries. I agree with you on that.

**Comment by rstoneback** [comment]
I've checked with SAMI.

```
In [8]: sami = pysat.Instrument('sami2py', 'sami2', file_format='u1p_{year:04d}{day:03d}.nc', update_files=True)                                                                                                            

In [9]: sami.load(2014, 2)                                                                                                                                                                                                  
/Users/russellstoneback/Code/pysat/pysat/_meta.py:617: UserWarning: Array elements are not allowed in meta. Dropping input : valid_range
  warnings.warn(' '.join(('Array elements are',

In [10]: sami.data                                                                                                                                                                                                          
Out[10]: 
<xarray.Dataset>
Dimensions:  (alt: 111, lat: 179, lon: 90, time: 96)
Coordinates:
  * lon      (lon) float32 -180.0 -175.95506 -171.91011 ... 175.95505 180.0
  * lat      (lat) float32 -89.0 -88.0 -87.0 -86.0 -85.0 ... 86.0 87.0 88.0 89.0
  * alt      (alt) float32 100.0 103.63471 107.30269 ... 1263.6216 1300.0
  * time     (time) datetime64[ns] 2019-01-02 ... 2019-01-02T23:44:59
Data variables:
    year     float32 ...
    day      float32 ...
    hrut     (time) float32 ...
    u1p      (time, alt, lat, lon) float32 ...

In [11]: sami.load(2014, 2, 2014, 4)                                                                                                                                                                                        
/Users/russellstoneback/Code/pysat/pysat/_meta.py:617: UserWarning: Array elements are not allowed in meta. Dropping input : valid_range
  warnings.warn(' '.join(('Array elements are',

In [12]: sami.data                                                                                                                                                                                                          
Out[12]: 
<xarray.Dataset>
Dimensions:  (alt: 111, lat: 179, lon: 90, time: 192)
Coordinates:
  * lon      (lon) float32 -180.0 -175.95506 -171.91011 ... 175.95505 180.0
  * lat      (lat) float32 -89.0 -88.0 -87.0 -86.0 -85.0 ... 86.0 87.0 88.0 89.0
  * alt      (alt) float32 100.0 103.63471 107.30269 ... 1263.6216 1300.0
  * time     (time) datetime64[ns] 2019-01-02 ... 2019-01-03T23:44:59
Data variables:
    year     (time) float32 2014.0 2014.0 2014.0 2014.0 ... 2014.0 2014.0 2014.0
    day      (time) float32 2.0 2.0 2.0 2.0 2.0 2.0 ... 3.0 3.0 3.0 3.0 3.0 3.0
    hrut     (time) float32 dask.array<chunksize=(96,), meta=np.ndarray>
    u1p      (time, alt, lat, lon) float32 dask.array<chunksize=(96, 111, 179, 90), meta=np.ndarray>

In [13]: sami.load(2014, 2, 2014, 5)                                                                                                                                                                                        
/Users/russellstoneback/Code/pysat/pysat/_meta.py:617: UserWarning: Array elements are not allowed in meta. Dropping input : valid_range
  warnings.warn(' '.join(('Array elements are',

In [14]: sami.data                                                                                                                                                                                                          
Out[14]: 
<xarray.Dataset>
Dimensions:  (alt: 111, lat: 179, lon: 90, time: 288)
Coordinates:
  * lon      (lon) float32 -180.0 -175.95506 -171.91011 ... 175.95505 180.0
  * lat      (lat) float32 -89.0 -88.0 -87.0 -86.0 -85.0 ... 86.0 87.0 88.0 89.0
  * alt      (alt) float32 100.0 103.63471 107.30269 ... 1263.6216 1300.0
  * time     (time) datetime64[ns] 2019-01-02 ... 2019-01-04T23:44:59
Data variables:
    year     (time) float32 2014.0 2014.0 2014.0 2014.0 ... 2014.0 2014.0 2014.0
    day      (time) float32 2.0 2.0 2.0 2.0 2.0 2.0 ... 4.0 4.0 4.0 4.0 4.0 4.0
    hrut     (time) float32 dask.array<chunksize=(96,), meta=np.ndarray>
    u1p      (time, alt, lat, lon) float32 dask.array<chunksize=(96, 111, 179, 90), meta=np.ndarray>
```

To get things to work I had to modify the sami2py_sami.py file for the SAMI files I have,
```
    data['time'] = [dt.datetime(2019, 1, 1)
                    + dt.timedelta(seconds=int(val * 86400.0))
                    for val in data['time'].values]
```

I also had to install a couple packages, `dask` and `toolz`, as well.

**Comment by aburrell** [comment]
What did you need `dask` and `toolz` for?

**Comment by rstoneback** [comment]
> What did you need `dask` and `toolz` for?

xarray is using them to load the files.

**Comment by rstoneback** [comment]
> > What did you need `dask` and `toolz` for?
> 
> xarray is using them to load the files.

Yeah. I actually first ran into this on a review when those lines were originally changed. I clearly forgot to follow up....

xarray doesn't include all packages in its requirements. In a sense we've already signed on for dask and toolz we just didn't know it. We may want to add it to pysat's list. dask was easy enough but the error for `toolz` pops up as missing `tlz`. Trying to install `tlz` doesn't work.

**Comment by rstoneback** [comment]
Oh, and the error is related to:
```
ImportError: cannot import name 'generate_instrument_list'[0m
```
which may be in work in #64?

**Comment by aburrell** [comment]
Hopefully!  I finally remembered to go make @jklenzing's suggested changes there thanks to this PR :-P. Travis is taking its sweet time, though.

**Comment by jklenzing** [comment]
The pytest issues should be fixed by the updates in #64.

**Comment by rstoneback** [comment]
Thanks for the fixes from #64. This is ready for re-review.

**Review by aburrell — APPROVED** [review]

**Comment by rstoneback** [comment]
Thanks @aburrell!

**Pull request merged**
