### PR TITLE
BUG: custom input changed

### PR DESCRIPTION
**Pull request by aburrell**
The way custom function input is specified changed to use `args` and `kwargs` in `pysat` PR 433: https://github.com/pysat/pysat/pull/433

This PR looked for all implementations of `custom` and updated them.  Addresses issue #45.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

This was found/tested by running `match.collect_inst_model_pairs` with longitude updating.

**Test Configuration**:
* Operating system: OS X Mojave
* Version number: 3.7.7
* Any details about your local setup that are relevant

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by aburrell** [comment]
Looks like there's been an update to the minimum versions that break things.  @jklenzing this seems like something you may have already solved elsewhere...

**Comment by jklenzing** [comment]
We ran into this with sami2py.  The core issue is that matplotlib 3.3.0rc1 requires numpy 1.16, but has not updated requirements in the pre-release code.  Options:
- Implement a fix similar to sami2py.  Custom matplotlib install for the minimum NEP 29 case
- NEP 29 only requires support of numpy 1.15 through July 23.  We could just drop it now in the tests, if it is unlikely we will release a new version before then.

**Comment by jklenzing** [comment]
I can put together a pull into this branch depending on what way you want to go.

**Comment by aburrell** [comment]
We aren't going to get a release put together in 10 days, so let's just drop it.  Probably cleanest to make a different pull into develop and then update this branch.

**Comment by aburrell** [comment]
Ready for a review @jklenzing

**Pull request merged**
