### PR TITLE
BUG: Updated dineof test file and name

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Pair to pull #102 

Updates DINEOFs file to the latest, with the correct filename.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details for
your test configuration

- Ran match example using this file

**Test Configuration**:
* MacOS
* Python 3.9
* Any details about your local setup that are relevant

# Checklist:

- [ ] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Review by aburrell — COMMENTED** [review]
Is the build expected to fail?

**Comment by rstoneback** [comment]
I do expect a failure in main since code and file are inconstant. However, current failure is related to netCDF4 and the pip install. Complaining about hdf5.

**Comment by rstoneback** [comment]
I double checked the code and the tests should pass. I also tried to restart the build on Travis but it wouldn't let me. Got the repeated message, Oh No! Can't start build.

**Comment by rstoneback** [comment]
Got the tests restarted but giving the same error.
```
Complete output (19 lines):
[356]()    Package hdf5 was not found in the pkg-config search path.
[357]()    Perhaps you should add the directory containing `hdf5.pc'
[358]()    to the PKG_CONFIG_PATH environment variable
[359]()    No package 'hdf5' found
[360]()    reading from setup.cfg...
[361]()
```

**Comment by aburrell** [comment]
Ah, this might be a travis issue that's solved on the develop branch.  If there's a paired PR going into develop we can use the CI there and let it fail here.

**Comment by rstoneback** [comment]
This goes along with #102. For some reason I'm not seeing anything on the right to otherwise link the two besides the mentions (updated description at top).

**Review by aburrell — APPROVED** [review]

**Pull request merged**
