### PR TITLE
BUG: Correct filename format str

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses #86

There is an inconsistency between example and code in terms of DINEOFs file names. Checking my local system, DINEOFs files are 'dineof_xxxx-xx-xx.nc'. The file I uploaded previously was `dineof-xxxx-xx-xx.nc`. So while on the call I claimed the format string in the code is bad, I think it is actually the uploaded file. 

This is not ready yet then.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details for
your test configuration

- Ran the match example with this file

**Test Configuration**:
* Operating system: MacOS
* Version number: Python 3.9
* Any details about your local setup that are relevant

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by aburrell** [comment]
Once you know which way you want the file formatted, ping me to review.

**Comment by rstoneback** [comment]
I updated the filename to match code and files used in other projects.

**Comment by rstoneback** [comment]
I updated the download link to the correct name, but the link points to main where the old filename still exists. Download is broken until merged into main.

**Comment by rstoneback** [comment]
This pull needs #103 to be incorporated into main before tests will pass here.

**Comment by rstoneback** [comment]
The doc link tests are having issues but the code is good.

**Pull request merged**
