### PR TITLE
TST: include test scripts in coverage reports

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

Includes test routines in coverage reports.

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Via Travis CI

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by jklenzing** [comment]
Failing because #40 needs to be merged in first to update the pysat interface.

**Comment by aburrell** [comment]
@jklenzing does this pull need the pip coveralls update?

**Comment by jklenzing** [comment]
This would have been a better place to put it.  I added it to #40 for some reason.

**Comment by jklenzing** [comment]
I remember now.  I stuck it in the other one since it successfully runs the tests due to syntax changes in pysat.

**Comment by aburrell** [comment]
Converting back to draft because testing indicates that more work needs to be done despite the merge of the upstream PR.

**Pull request merged**
