### PR TITLE
Match doc

### PR DESCRIPTION
**Pull request by aburrell**
# Description

Improves docstring style, adds a match utility example to the documentation, improves documentation style, and adds a zenodo.json file.  Partially addresses #35.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update

# How Has This Been Tested?

Running the documentation example and creating the documents locally.

**Test Configuration**:
* Operating system: OS X Mojave
* Version number: 3.9
* Any details about your local setup that are relevant

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by aburrell** [comment]
@jklenzing the SAMI2py loading unit tests aren't passing.  Want to take a look?

**Comment by jklenzing** [comment]
The root of the issue is that the 'ut' parameter  in sami2py is being saved as ns instead of hours.  Not sure why this is happening

**Comment by jklenzing** [comment]
@aburrell, I figured out what broke.  Adding the metadata for sami2 triggered a change in the load command within xarray, since it will interpret things like 'hours' as a timedelta.  We can turn this off by passing the argument 'decode_timedelta=False' into the load statement, but this has to be done on the pysat side.  Options:
- Update in pysat and pass variable through here
- Directly use xarray.load_dataset here rather than the pysat load.  This will not load metadata correctly
- Use the new math proposed in #80.  pysat needs a time, so we can just calculate from ns rather than hours

**Comment by jklenzing** [comment]
Documented pysat implications at pysat/pysat#823

**Comment by jklenzing** [comment]
release candidate for sami2py is up.  Replaced line 185 in the sami2py instrument here with 
```
        remote_path = 'blob/rc0.2.4/sami2py/tests/test_data/'
```
and ran tests locally.  Everything is working as expected.  Once the RC is approved, the sami2py tests here should work without modification.

**Review by jklenzing — APPROVED** [review]
some doc tests failed presumably because of a server hiccup.  restarted.

**Pull request merged**
