### PR TITLE
ENH: Updated DINEOF test file

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses #76

Updated the DINEOF example model to include more information. Inspired by an existing model file. 

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Visual Inspection of the produced file.

**Test Configuration**:
* MacOS 10.15.4

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by aburrell** [comment]
Should this be rebased into `match_docs`?

**Comment by aburrell** [comment]
Otherwise, I think it looks like it fulfills the necessary requirements 🐴

**Comment by rstoneback** [comment]
> Ok, took a quick look and could you change all the `sami` variable names to `model`? That would make it more general/test-y. Not sure how hard that is to change in your netCDF file creation.

Yes. That makes much more sense.

**Comment by rstoneback** [comment]
Updated.

**Review by aburrell — APPROVED** [review]

**Pull request merged**
