### PR TITLE
ENH: Added test data

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses #(issue)

Includes test data at the master level so that other code pulls can be completed now rather than later.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

File is present.

# Checklist:

- [ ] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
Tests don't currently pass for main so this pull is not breaking anything.

**Comment by rstoneback** [comment]
Thanks for the approval on #73 but to get this in without using admin privileges it requires a review.

**Comment by aburrell** [comment]
Ah, I see what you're trying to do here.  In #73 I was just asking for an issue/PR to merge in once we had a release candidate.  Why do you want to do it this way?  Is it easier?

**Comment by rstoneback** [comment]
> Ah, I see what you're trying to do here. In #73 I was just asking for an issue/PR to merge in once we had a release candidate. Why do you want to do it this way? Is it easier?

I can do the issue if you prefer. My thinking was instead of doing x work on an issue and y work later to close it, let's do less than x+y work now and solve it 'for all time'.

**Review by aburrell — APPROVED** [review]

**Pull request merged**
