### PR TITLE
Update sami2py_sami2.py

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

Should adjust assumptions for sami2py with new files.  An issue needs to be created at sami2py as the output is not particularly useful the way xarray is saving it.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

tested locally by trying to load the sami2py test file
```
import pysat
sami2 = pysat.Instrument('sami2py', 'sami2', tag='test')
sami2.load(2019, 1)
```

**Test Configuration**:
* Mac OS X 10.15.7
* python 3.8.2
* xarray 0.18.0

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by jklenzing** [comment]
@aburrell, Looking into

**Comment by jklenzing** [comment]
Reopening for discussion

**Comment by aburrell** [comment]
So, I guess the question is, do we want to go back into pysat and fix it so that this update isn't needed or make this update?  I liked the old behaviour better, since it keeps the data stored the way it is in the file.  Thoughts?

**Comment by jklenzing** [comment]
We would need to get that into the new version before tests start working here.  I'm still not quite sure of all the implications of updating the keyword.  The long-term solution in sami2py is to output the time there so we don't have to calculate a time variable here.  Depending on the timeframe for pysat 3.0.1, we might just update this here since these lines would be removed eventually.

We could also check for variable type and calculate accordingly.  I'm somewhat concerned about the ominous phrase "This keyword may not be supported by all the backends." in the xarray docstrings.  We may get different responses based on xarray version.

**Comment by jklenzing** [comment]
or, I could always push a quick patch to sami2py updating the metadata accordingly to avoid this problem for the time being.

**Comment by aburrell** [comment]
> "This keyword may not be supported by all the backends." in the xarray docstrings. 

:bat very scary.

I like the long term solution you present (having datetime in sami2py output).  It's useful for lots of other things, too.  Ok, I think the best scenario here for the moment is to test what kind of data is stored and then apply the correct correction.  The sami2py patch would probably also be good for your users.

**Comment by jklenzing** [comment]
A quick local test shows that updating the ut units attribute to 'hrs' instead of 'hours' will load as expected.  It's also more consistent with slt that way.

**Comment by jklenzing** [comment]
If I push through the patch, this branch is not needed.  However, to be thorough, we could add the type check.

**Comment by aburrell** [comment]
Let's close this once the patch goes through.  We don't want to introduce a type check that never gets raised if things are working as desired.

**Comment by jklenzing** [comment]
v0.2.4 of sami2py is released.

**Pull request closed without merging**
